#!/bin/bash

usage_exit() {
        echo "Usage: $0 [-w] name" 1>&2
        exit 1
}
outputs="outputs"

while getopts wh option
do
    case $option in
        w)
            outputs="cases"
            ;;
        h)
            usage_exit
            ;;
    esac
done

shift $((OPTIND - 1))

rm -rf tests/${outputs}
mkdir -p tests/cases tests/${outputs}
cases=$(ls tests/cases)
if [ ! -z $1 ];then
    cases=$1
fi
errors=0

for case in $cases
do
    out=$(ansible-playbook ./tests/test.yml -i ./tests/hosts -t $case -D -e prefix_dir="${outputs}/${case}" -e ansible_unit_test=true)
    result=$?

    if diff -uNr tests/cases/${case} tests/${outputs}/${case} >/dev/null 2>&1 ;then
        echo -n "."
    else
        echo $case
        echo
        diff -uNr tests/cases/${case} tests/${outputs}/${case}
        errors=$(( errors+1 ))
    fi
done

if [ $errors -eq 0 ]
then
    echo " ok"
else
    echo "${errors} error(s)"
fi
exit $errors
